/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  automationSidebar: [{type: 'autogenerated', dirName: 'automation', label: '联动设置'}],
  devicesSidebar: [{type: 'autogenerated', dirName: 'devices', label: '设备百科'}],
  extendSidebar: [{type: 'autogenerated', dirName: 'extend', label: '进阶教程'}],
  demoSidebar: [{type: 'autogenerated', dirName: 'demo', label: '模板'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
